name: CI
on:
  push:
  pull_request:
    branches:
      - master

jobs:

  check:
    name: Build checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo-fmt for formatting fixes
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo-clippy for linter issues
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build package
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
